version: "3.5"

services:
  java:
    container_name: digitalizacion_java
    build: .
    environment:
      DB_HOST: "${DB_HOST}"
      DB_PASS: "${DB_PASS}"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USER: "${DB_USER}"
      DEBUG: "${DEBUG}"
      SERVER_PORT: "${SERVER_PORT}"
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet_network
