version: "3.8"

services:
  mysqldb:
    container_name: db_digitalizacion
    image: mariadb:10.9.3
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_PORT:3306
    volumes:
      - db_digitalizacion:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    env_file: ./.env
    ports:
      - $JAVA_PORT:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$DB_PORT/$DB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$DB_USER",
        "spring.datasource.password" : "$DB_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "validate"
      }'
    stdin_open: true
    tty: true

volumes:
  db_digitalizacion:
